### ISSUE TITLE
App refresh on route other than index gives 404 error, after deployment

### ISSUE THREAD

**Issue by shadow-fox** [stefanpenner/ember-app-kit#486]
hi,
 I have posted the question on stackoverflow here is the link:: 
http://stackoverflow.com/questions/21751371/emberjs-application-refresh-on-route-other-than-index-gives-404-error

Issues that I am facing as of now::
When I hit the root url, I can see the index page, while going to any other route from links that are present in the index page it works fine and lets me go to that page. The issue issue occurs when I try to hit refresh on the that page itself.

First I thought it is due to permissions error, but it is only single html file and js and css are loading properly. Then thought might be htaccess issue so tried to insert one , but no effects after that also.

**Comment by cfator** [comment]
Finding this problem when having the UI served up from Ember Server and using locationType: 'auto'.  Seems like the rules to serve index.html for any descendent routes would be independent of this ("ember-cli": "1.13.13").  This completely breaks livereload because as soon as a refresh occurs you get "Cannot GET /[some url]"

**Comment by Matty70** [comment]
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase /
  RewriteRule ^index\.html$ - [L]
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule . /index.html [L]
</IfModule>

this worked for me thanks for thr solution
